CREATE DATABASE PCLINICS_Manha
GO
Use PCLINICS_Manha
GO
CREATE TABLE Clinica (
	IdClinica	INT PRIMARY KEY IDENTITY,
	RazaoSocial	VARCHAR(30),
	Endereco	VARCHAR(60)
)
GO
CREATE TABLE Dono (
	IdDono		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(100)
)
GO
CREATE TABLE TipoPet (
	IdTipoPet	INT PRIMARY KEY IDENTITY,
	Titulo		VARCHAR (30)
)
GO
CREATE TABLE Raca (
	IdRaca		INT PRIMARY KEY IDENTITY,
	Titulo		VARCHAR (30),
	IdTipoPet	INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)
)
GO
CREATE TABLE Veterinario (
	IdVeterinario INT PRIMARY KEY IDENTITY,
	Nome		  VARCHAR (100),
	IdClinica	  INT FOREIGN KEY REFERENCES Clinica(IdClinica)
)
GO
CREATE TABLE Pet (
	IdPet		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(100),
	Telefone	VARCHAR(10),
	Porte		VARCHAR(10),
	IdRaca		INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono		INT FOREIGN KEY REFERENCES Dono(IdDono)
)
GO
CREATE TABLE Atendimento (
	IdAtendimento INT PRIMARY KEY IDENTITY,
	Dia			  DATE,
	Discricao	  VARCHAR(10),
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet		  INT FOREIGN KEY REFERENCES Pet(IdPet)
)